version: '3'

services:
###> doctrine/doctrine-bundle ###
  mailer:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fruit
      # You should definitely change the password in production
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: admin
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
